analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.490223
  lightness: 0.505587
  rhythmicContrast: 0.50419
  saturation: 0.498603
cta: {}
layout_spectrum: 0.667598
name: 'HollyHood Productions, Inc.'
opengraph: {}
purpose: {}
typography_spectrum: 0.916201
