name: 'HollyHood Productions, Inc.'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.916201
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfe'
    - '#0e100f'
    - '#4e534f'
    - '#c1c2c2'
    - '#858786'
  brandStrength: 0.490223
  lightness: 0.505587
  saturation: 0.498603
  rhythmicContrast: 0.50419
purpose:
  - name: null
    item: null
    url: null
